version: '2'
services:
  parity:
    image: parity/parity:v2.0.5
    command:
    - --chain
    - tobalaba
    - --jsonrpc-apis
    - all
    - --log-file
    - /app/parity.log
    volumes:
    - ./logs/:/app/:rw
  origin-consumer:
    build: ./consumer
  origin-producer:
    build: ./producer