version: '2'
services:
  bond:
    build: ./bond
    depends_on:
      - ewf-client
  ewf-client:
    build: ./ewf-client
    mem_limit: 600m
    healthcheck:
      test:
      - "CMD"
      - "/health"
      interval: 30s
      timeout: 10s
      retries: 10

