version: '2.3'
services:
  parity:
    mem_limit: 550m
    image: parity/parity:latest
    command:
    - -d
    - /data
    - --cache
    - "256"
    - --no-warp
    - --light
    - --log-file 
    - /data/parity.log
    - --jsonrpc-apis all
    volumes:
    - /opt/slockit/data/parity:/data
    restart: on-failure
    healthcheck:
      test:
      - "CMD"
      - "/health"
      interval: 30s
      timeout: 10s
      retries: 10