version: '2.3'
services:
  parity:
    mem_limit: 550m
    image: parity/parity:v1.9.3
    command:
    - -d
    - /data
    - --cache
    - "256"
    - --log-file 
    - /data/parity.log
    - --jsonrpc-apis all
    - --reserved-peers
    - /data/tobalaba-peers
    - --chain
    - /data/chain.json
    volumes:
    - /opt/slockit/data/parity:/data
    restart: on-failure
    healthcheck:
      test:
      - "CMD"
      - "/health"
      interval: 30s
      timeout: 10s
      retries: 10